## Serve the MkDocs website.
serve:
	mkdocs serve

## Build the website and generate schema pages.
build:
	mkdocs build

SDK_PATH ?= ../go-sdk
SPEC_PATH ?= ../OpenSLO

## Import the specification after updating its upstream README.
generate/specification:
	python specification.py "$(SPEC_PATH)/README.md"

## Import the manifest generated by the OpenSLO Go SDK.
generate/schema:
	python schema.py "$(SDK_PATH)/docs/manifest.json"

## Run checks.
check: check/python test

## Run Python checks.
check/python:
	ruff check .

## Compare the manifest with the pinned SDK's fields and govy plans.
check/schema-source:
	cd tools/schema-check && go test -count=1 ./...

## Test schema generation through MkDocs.
test:
	python -m unittest discover -s tests

## Format files.
format: format/python

## Format Python files.
format/python:
	ruff format .
