# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: OpenSLO
site_url: https://openslo.com
theme:
  name: material
  favicon: assets/images/favicon.png
  logo: assets/images/logo2.svg
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - search.highlight
    - search.share
nav:
  - Home: index.md
  - About: about.md
  - Blog:
    - blog/index.md
plugins:
  - blog
  - search
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_css:
  - blog/extra.css
extra:
  generator: false
  social:
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/openslo/shared_invite/zt-1ecraohaa-fqj3C52WF~1zQbwKD8LeMw
    - icon: fontawesome/brands/github 
      link: https://github.com/OpenSLO/OpenSLO
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/openslo_
repo_url: https://github.com/OpenSLO/OpenSLO
repo_name: OpenSLO
copyright: "&copy; 2025 The OpenSLO Contributors | Documentation Distributed under CC BY 4.0 | All Rights Reserved"
